
insert into schoolManager.courses (course_name, description) values ('Alchemy','the study of transmutation of substances into other forms.');
insert into schoolManager.courses (course_name, description) values ('Herbology','the study of magical plants and how to take care of, utilise and combat them.');
insert into schoolManager.courses (course_name, description) values ('History of Magic','the study of magical history.');
insert into schoolManager.courses (course_name, description) values ('Potions','the art of creating mixtures with magical effects.');
insert into schoolManager.courses (course_name, description) values ('Muggle Studies','the study of the Muggle culture "from a wizarding point of view".');
insert into schoolManager.courses (course_name, description) values ('Dark Arts','the study of defensive techniques to defend against the Dark Arts.');
insert into schoolManager.courses (course_name, description) values ('Charms','the study of spells concerned with giving an object new properties.');
insert into schoolManager.courses (course_name, description) values ('Flying','the study of flying of broomsticks.');
insert into schoolManager.courses (course_name, description) values ('Magical Theory','the study of  magic from a purely theoretical view.');
insert into schoolManager.courses (course_name, description) values ('Ghoul Studies','the study of ghouls  and  other similar creatures.');

insert into schoolManager.groups (group_name) values ('WS-75');
insert into schoolManager.groups (group_name) values ('CE-46');
insert into schoolManager.groups (group_name) values ('IX-48');
insert into schoolManager.groups (group_name) values ('UC-22');
insert into schoolManager.groups (group_name) values ('XF-19');
insert into schoolManager.groups (group_name) values ('LU-69');
insert into schoolManager.groups (group_name) values ('GP-56');
insert into schoolManager.groups (group_name) values ('NB-67');
insert into schoolManager.groups (group_name) values ('JO-93');
insert into schoolManager.groups (group_name) values ('SG-21');

insert into schoolManager.students (first_name, last_name) values ('Lisa','Nott');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Dean','Bones');
insert into schoolManager.students (first_name, last_name) values ('Justin','Boot');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Mandy','Boot');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Patil');
insert into schoolManager.students (first_name, last_name) values ('Dean','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Dean','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Granger');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Harry','Patil');
insert into schoolManager.students (first_name, last_name) values ('Michael','Corner');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Terry','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Patil');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Patil');
insert into schoolManager.students (first_name, last_name) values ('Terry','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Neville','Goldstein');
insert into schoolManager.students (first_name, last_name) values ('Michael','Boot');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Corner');
insert into schoolManager.students (first_name, last_name) values ('Terry','Granger');
insert into schoolManager.students (first_name, last_name) values ('Padma','Patil');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Susan','Patil');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Boot');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Bones');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Boot');
insert into schoolManager.students (first_name, last_name) values ('Hermione','Nott');
insert into schoolManager.students (first_name, last_name) values ('Harry','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Bones');
insert into schoolManager.students (first_name, last_name) values ('Dean','Boot');
insert into schoolManager.students (first_name, last_name) values ('Hermione','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Neville','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Terry','Nott');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Patil');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Boot');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Michael','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Nott');
insert into schoolManager.students (first_name, last_name) values ('Terry','Bones');
insert into schoolManager.students (first_name, last_name) values ('Neville','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Susan','Brown');
insert into schoolManager.students (first_name, last_name) values ('Terry','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Michael','Nott');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Potter');
insert into schoolManager.students (first_name, last_name) values ('Neville','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Hermione','Nott');
insert into schoolManager.students (first_name, last_name) values ('Padma','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Harry','Goldstein');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Potter');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Nott');
insert into schoolManager.students (first_name, last_name) values ('Neville','Granger');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Brown');
insert into schoolManager.students (first_name, last_name) values ('Padma','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Susan','Potter');
insert into schoolManager.students (first_name, last_name) values ('Susan','Nott');
insert into schoolManager.students (first_name, last_name) values ('Neville','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Justin','Patil');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Brown');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Mandy','Boot');
insert into schoolManager.students (first_name, last_name) values ('Susan','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Justin','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Padma','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Susan','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Justin','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Susan','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Nott');
insert into schoolManager.students (first_name, last_name) values ('Hermione','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Patil');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Brown');
insert into schoolManager.students (first_name, last_name) values ('Harry','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Corner');
insert into schoolManager.students (first_name, last_name) values ('Susan','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Susan','Brown');
insert into schoolManager.students (first_name, last_name) values ('Padma','Patil');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Brown');
insert into schoolManager.students (first_name, last_name) values ('Justin','Granger');
insert into schoolManager.students (first_name, last_name) values ('Susan','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Mandy','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Corner');
insert into schoolManager.students (first_name, last_name) values ('Terry','Corner');
insert into schoolManager.students (first_name, last_name) values ('Mandy','Granger');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Justin','Granger');
insert into schoolManager.students (first_name, last_name) values ('Terry','Nott');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Boot');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Granger');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Justin','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Padma','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Dean','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Brown');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Corner');
insert into schoolManager.students (first_name, last_name) values ('Justin','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Harry','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Boot');
insert into schoolManager.students (first_name, last_name) values ('Harry','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Brown');
insert into schoolManager.students (first_name, last_name) values ('Justin','Bones');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Justin','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Justin','Granger');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Boot');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Granger');
insert into schoolManager.students (first_name, last_name) values ('Terry','Potter');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Goldstein');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Granger');
insert into schoolManager.students (first_name, last_name) values ('Harry','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Terry','Patil');
insert into schoolManager.students (first_name, last_name) values ('Harry','Corner');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Granger');
insert into schoolManager.students (first_name, last_name) values ('Mandy','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Justin','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Boot');
insert into schoolManager.students (first_name, last_name) values ('Michael','Patil');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Bones');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Padma','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Abbott');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Brown');
insert into schoolManager.students (first_name, last_name) values ('Susan','Boot');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Granger');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Corner');
insert into schoolManager.students (first_name, last_name) values ('Harry','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Susan','Macmillan');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Goldstein');
insert into schoolManager.students (first_name, last_name) values ('Justin','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Hannah','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Potter');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Brocklehurst');
insert into schoolManager.students (first_name, last_name) values ('Terry','Patil');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Brown');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Potter');
insert into schoolManager.students (first_name, last_name) values ('Padma','Bones');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Brown');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Boot');
insert into schoolManager.students (first_name, last_name) values ('Pansy','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Ronald','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Hermione','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Michael','Bones');
insert into schoolManager.students (first_name, last_name) values ('Dean','Finch-Fletchley');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Nott');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Dean','Corner');
insert into schoolManager.students (first_name, last_name) values ('Seamus','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Hermione','Nott');
insert into schoolManager.students (first_name, last_name) values ('Terry','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Thomas');
insert into schoolManager.students (first_name, last_name) values ('Anthony','Nott');
insert into schoolManager.students (first_name, last_name) values ('Parvati','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Ernie','Granger');
insert into schoolManager.students (first_name, last_name) values ('Harry','Finnigan');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Potter');
insert into schoolManager.students (first_name, last_name) values ('Michael','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Terry','Weasley');
insert into schoolManager.students (first_name, last_name) values ('Padma','Longbottom');
insert into schoolManager.students (first_name, last_name) values ('Neville','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Lisa','Turpin');
insert into schoolManager.students (first_name, last_name) values ('Theodore','Parkinson');
insert into schoolManager.students (first_name, last_name) values ('Lavender','Thomas');


